apiVersion: v1
kind: Service
metadata:
  name: dwrest2
  labels:
    app: dropwizard-restful-test2
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 8080
  selector:
    app: dropwizard-restful-test2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dropwizard-deployment
  labels:
    app: dropwizard-restful-test2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dropwizard-restful-test2
  template:
    metadata:
      labels:
        app: dropwizard-restful-test2
    spec:
      containers:
        - name: dropwizard-restful-test2
          image: lucas2010/dropwizardrestfultest2
          ports:
            - containerPort: 8080
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                      - dropwizard-restful-test2
                topologyKey: "kubernetes.io/hostname"